---
title: "PRL Experience"
output: html_notebook
---

```{r data import}
#import data 
dat <-read.csv("~/Documents/projects/PRL_experience/prl_experience_brains_data_updated.csv", stringsAsFactors = F)
```

```{r sample sizes}
#sample size
colnames(dat)

dat %>%
  filter(active_nest_collection == 0) %>%
  group_by(experience_chicks, sex) %>%
  tally()
```

```{r}
#experienced birds: ranges of chicks hatched
dat %>%
  filter(experience_chicks == 1) %>%
  group_by(nest_no = cut(total_chicks, breaks = seq(0,20,5)), sex) %>%
  tally()

#inexperienced birds by age
dat %>%
  filter(active_nest_collection == 0) %>%
  drop_na(age_years) %>%
  filter(experience_nests == 0) %>%
  group_by(age = cut(age_years, breaks = seq(0,4,1)), sex) %>%
  tally()
```


```{r all brains sample}
#all birds sample size

dat %>%
  filter(active_nest_collection == 0) %>% 
  group_by(experience_chicks, age = cut(age_years, breaks = seq(0,4,1)), sex) %>%
  tally()

id_list_for_export <-
dat %>%
  filter(active_nest_collection == 0) %>%
  mutate(age_group = cut(age_years, breaks = seq(0,4,1))) %>%
  select(id, sex, experience_chicks, age_years, age_group) %>%
  arrange(id)

write.csv(id_list_for_export,"~/Documents/projects/PRL_experience/experience_brains_to_slice_with_id.csv")
```

```{r}
#experienced birds: by nest no and age 
dat %>%
  drop_na(age_years)%>%
  filter(experience == "y") %>%
  group_by(nest_no = cut(nest_count, breaks = seq(0,30,10)), age = cut(age_years, breaks = seq(0,4,1))) %>%
  tally()

#birds with no active nests: by experience 
dat %>%
  filter(active_nest_at_collection == "n") %>%
  mutate(hadChicks = ifelse(chicks_hatched > 0, "1", "0")) %>%
  group_by(sex, hadChicks) %>%
  tally()


dat %>%
  filter(active_nest_at_collection == "n") %>%
  mutate(hadChicks = ifelse(chicks_hatched > 0, "1", "0")) %>%
  mutate(olderThan2 = ifelse(age_years >2, "1", "0")) %>%
  group_by(sex, hadChicks, olderThan2) %>%
  tally()

#experienced birds: by nest no and age 
dat %>%
  filter(active_nest_at_collection == "n") %>%
  mutate(hadChicks = ifelse(chicks_hatched > 0, "1", "0")) %>%
  group_by(sex, hadChicks, age = cut(age_years, breaks = seq(0,4,1))) %>%
  tally()
```
what is reproductive maturity in these birds (i.e. what is the youngest ages we have seen first nests)?
(I totally calculated this once)
get birds older than that age but younger than 1 years old. 
