---
title: "ROPI Database Searcher"
author: "V.S. Farrar"
date: 'Code created: 10/16/2020'
output:
  html_document: default
  pdf_document: default
---

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)
library(lubridate)
library(zoo) #parses month/year dates
```

### Data Files Used 
Update the below data files with the most up-to-date BandingRecords and NestSummary files from FileMaker pro. 

```{r import data, echo = FALSE}
#import Banding Records (direct export from FileMaker Pro)
bands <- read.csv("~/Documents/projects/PRL_experience/data_for_experimental_design_culling/2021-03-05_BandingRecords_all.csv", stringsAsFactors = FALSE)

#import Nest Summary (direct export from FileMaker Pro)
nests <- read.csv("~/Documents/projects/PRL_experience/data_for_experimental_design_culling/2021-03-05_NestSummary_all.csv", stringsAsFactors = FALSE)

```

```{r dataset cleanup,echo = FALSE }
#dataset cleanup 

#clean up BandingRecords data

#select relevant columns
bands<-bands %>%
  select(BandNum, c_DateHatch, Cage, ColorBand, Date_Deceased, Date_Hatch, Room, Sex) 

#convert to date
bands$DateHatch<-as.Date(bands$c_DateHatch,format = "%m/%d/%Y")
bands$Date_Deceased<-as.Date(bands$Date_Deceased,format = "%m/%d/%Y")


#clean up NestSummary data

#extract numerical band numbers and then create a combo of parent_ids for searching
nests<- nests %>%
  mutate(id1 = str_extract(AdultId_1BandNum, "([[:digit:]]+)"), 
         id2 = str_extract(AdultId_2BandNum, "([[:digit:]]+)")) %>%
  mutate(parent_ids = mapply(c, id1, id2, SIMPLIFY = F))
```

## Date of Search
```{r todays date, echo = FALSE}
#grab current date using Sys.Date()
current_date <- as.Date(Sys.Date(), format = "%m/%d/%Y")

print(paste0("Current date when searched: ", current_date))
```

```{r bands of living birds, echo = FALSE}
#create list of birds that are alive today

bands_alive <- bands %>%
  filter(is.na(Date_Deceased)) %>% #has no Date_Deceased date
  filter(!is.na(BandNum)) %>% #has a Band Number
  mutate(age_days = difftime(current_date, DateHatch, unit = "days")) #calculate current age from hatch
```

```{r gather nest experience data, echo = FALSE}

#grab Band Numbers for all birds alive currently 

all_bands <-as.character(bands_alive$BandNum) #convert to character for search

#initialize empty vectors
band_combo <- vector() 
nest_count <- vector()

for (i in 1:length(all_bands)){ 
    band_combo[i] <- all_bands[i] 
    nest_count[i]<- length(grep(all_bands[i],nests$parent_ids)) #get # of rows (nests) where bird was parent
} 

#put the two vectors together 
birds_alive_exp<- data.frame(cbind(band_combo, nest_count)) 

#convert to as character for join
birds_alive_exp$band_combo<-as.character(birds_alive_exp$band_combo)
bands_alive$BandNum<-as.character(bands_alive$BandNum)

#join for experience and age in one dataset
living_birds <- 
  right_join(bands_alive, birds_alive_exp, by = c("BandNum" = "band_combo")) %>%
  mutate(nest_count = as.numeric(as.character(nest_count))) %>%
  mutate(age_years = as.numeric(age_days)/365) %>%
  mutate(Sex =  case_when(grepl("m", Sex) ~ "m", #clean up sex data for readability
                            grepl("f", Sex) ~"f")) %>%
  select(Room, Cage, BandNum, everything()) %>%
  arrange(Room, Cage, Sex)

```

```{r more detailed experience info, echo=FALSE, message=FALSE, warning=FALSE}
#get more detailed experience information on eggs, hatches, and fledgelings 

#make only one parental id
  
parent1_nest<- nests %>% select(-id2) %>% rename("id" = "id1")
parent2_nest<- nests %>% select(-id1) %>% rename("id" = "id2")

all_nests <- rbind(parent1_nest, parent2_nest) 


#nests_by_bird gives all nests, eggs, chicks and fledgelings for a band number 

nests_by_bird <-
all_nests %>%
  filter(!is.na(id)) %>% #exclude nests without parent ids
  #filter(as.numeric(id) > 200) %>%
  group_by(id) %>%
  summarise(nests = n(), 
            eggs = sum(NumEggsLaid, na.rm = T), 
            chicks = sum(as.numeric(NumChicksHatched), na.rm = T), 
            fledge = sum(as.numeric(NumChicksFledged), na.rm = T)) %>%
  arrange(as.numeric(id))


#join detailed experience info (nest_info) with living_birds dataset 
  #10/17/2020 : nest_count and nests now match. 

birds <- left_join(living_birds, nests_by_bird, by = c("BandNum" = "id")) 

#now all info in one dataframe:
#colnames(birds)
```

```{r search active nests, echo = FALSE}
#search active nests 
active_nests <- 
  all_nests %>%
  mutate(d_Inactive = as.Date(d_Inactive, format = "%m/%d/%Y"),
         d_FirstEgg = as.Date(d_FirstEgg, format = "%m/%d/%Y")) %>% #convert key dates
  filter(is.na(d_Inactive), year(d_FirstEgg) == 2020) %>%  #no inactive date, must be in current year
  select(X_kP_NestId, RoomNum, CageNum,id,d_FirstEgg) %>%  #select relevant variables
  mutate(time_point = difftime(current_date, d_FirstEgg, unit = "days"))  #calculate days since lay of current nest
  
```


# Search Results: 

## Query:

```{r search query, paged.print=TRUE}
#Edit these searches to grab the data you are interested in. 
#To see variables you can filter by, use 
#colnames(birds). 

# birds %>%
#   filter(nests >10, 
#          Room == "3",
#          Sex == "f") %>%
#  arrange(Sex, desc(age_days)) %>%
#   select(Room, Cage, BandNum, ColorBand, Sex, age_years,nests, chicks) %>%
#   left_join(., active_nests, by = c("BandNum" = "id")) #join active nest effort data with bird data 



birds %>%
  filter( Room == "3") %>%
 arrange(Sex, chicks) %>%
  mutate(ActivelyBreeding = ifelse(BandNum %in% active_nests$id, 1, 0)) %>% #see if birds are actively breeding
  filter(between(age_years, 1,2)) %>%
  filter(ActivelyBreeding == 0) %>% #select birds that are not actively breeding
  filter(chicks == 0 & eggs <= 10) %>%
  select(-Date_Deceased, -Date_Hatch, -age_days)

```
```{r}
birds %>%
  filter( Room == "3") %>%
 arrange(Sex, age_years) %>%
  mutate(ActivelyBreeding = ifelse(BandNum %in% active_nests$id, 1, 0)) %>% #see if birds are actively breeding
  filter(between(age_years, 1,2)) %>%
  filter(ActivelyBreeding == 0) %>% #select birds that are not actively breeding
  filter(chicks >= 1) %>%
  select(-Date_Deceased, -Date_Hatch, -age_days)
```





